version: '3.8'
services:
  redis:
    image: redis:7-alpine
    container_name: fisiomove_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    image: python:3.11-slim
    container_name: fisiomove_backend
    working_dir: /app
    volumes:
      - ./:/app
    command: bash -lc "pip install -r requirements.txt && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    depends_on:
      - redis

volumes:
  redis_data:
